name: device
description: Data model for a device with various fields and geographical positions data
homepage: https://github.com/synw/device
version: 0.2.0

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  geopoint: ^0.7.1
  geodf: ^0.2.0
